language: java
sudo: false
script: mvn clean install
notifications:
  email:
    recipients:
      - emre.akkaya@agem.com.tr
      - ismail.basaran@tubitak.gov.tr
      - volkan.sahin@agem.com.tr
      - caner.feyzullahoglu@agem.com.tr
      - oner.unal@agem.com.tr
